### ISSUE TITLE
Integration step fails

### ISSUE THREAD

**Issue by BoxWong** [Yijia-Jiang/scATAnno-main#2]
Hi Yijia,
I've got a problem trying to integrate the reference adata (PBMC data downloaded from your dropbox link) with my own PBMC scATAC-seq data processed with quickATAC while the query data that I downloaded from dropbox went just fine.

1. So the problem is that the integration failed due to different vars in reference dataset and my own dataset. The code I ran was:

`integrated_adata1 = scATAnno_assignment.scATAnno_integrate(reference_data, query_data1, variable_prefix = "Pub", sample_size = 25000)`
and the error message was:
_ValueError: Adatas have different variables. Please specify join_vars='inner' for intersection._

2. I then tried running quickATAC with the peak files I exported from your reference dataset and generated new output. After trying to integrate the newly generated files with the reference dataset, it still throws the same error:

_ValueError: Adatas have different variables. Please specify join_vars='inner' for intersection._

3. Since the n_var of my data is smaller than that of the reference dataset, I subsetted the reference data by:

`sub_ref_data = reference_data[:, (query_data2.var.index & reference_data.var.index)]`
and did the integration again:
`integrated_adata2_subref = scATAnno_assignment.scATAnno_integrate(sub_ref_data, query_data2, variable_prefix = "Pub", sample_size = 25000)`

Now the 'Compute similarity matrix' step seems to be fine but the normalization step went wrong again and the error was different from the previous one:
_PanicException: called `Result::unwrap()` on an `Err` value: TooSteep_

PS: I would also like to mention that I changed your script (scATAnno_integration.py) and added the parameter "join_vars = 'inner'" to line 44 which caused the problem. Doing this also gave me the same error:
_PanicException: called `Result::unwrap()` on an `Err` value: TooSteep_

Sorry for the lengthy text and looking forward to your input.

Best,
Xin

**Comment by Yijia-Jiang** [comment]
Hi Xin, the integration failed since the peaks are not unified for reference and query.  We are working on a script for using quickATAC for scATAnno and will post it soon.

**Comment by Yijia-Jiang** [comment]
Hi Xin, we have uploaded a script to preprocess your PBMC scATAC-seq data (https://github.com/Yijia-Jiang/scATAnno-main/blob/main/prep_data/RunPBMC.sh).

To prepare for the PBMC peak matrix, you will need to use QuickATAC (https://github.com/AllenWLynch/QuickATAC/tree/main/quickatac). Then you can use the script RunPBMC.sh to get matrix for your query scATAC data.

Feel free to let me know if you have any questions.

**Comment by trit6611** [comment]
Hello Yijia,

I am trying the scATAnno package and ran into the exact same issue highlighted by Xin. Unfortunately, I cannot access the RubPBMC.sh data to troubleshoot. Could you please reupload the file or offer some additional guidance to overcome this issue? 

Thank you very much for your help and time!

**Comment by trit6611** [comment]
Sorry. I realized my comment was a little too broad, so I will write a much more detailed description. I followed your build_reference.sh instructions on SU008_Tumor_Pre fragments.tsv.gz from GSE129785. Then, I followed your prepare_query.sh instructions for my own dataset using the peaks.bed file from the reference. I then loaded my reference and query datasets following your TNBC tutorial and confirmed that my reference and query had the same n_vars as I wanted to avoid Xin's issue of different n_vars. 

This is my outputs when I print:
reference_data: AnnData object with n_obs × n_vars = 788 × 116521
obs: 'cell type', 'tissue', 'dataset', 'n_fragments_in_peaks', 'n_background_fragments', 'FRIP'

query_data: AnnData object with n_obs × n_vars = 48400 × 116521
obs: 'cell type', 'tissue', 'dataset'

Upon running the integration code, I get a similar error to Xin still, despite n_vars being same dimension:
Compute similarity matrix
ral.py:698: RuntimeWarning: invalid value encountered in true_divide
  d /= t
Normalization
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: TooSteep', src/utils.rs:161:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "SnapATC2_spectral.py", line 480, in spectral
    model.fit(S)   # fix reference; save model as object
  File "SnapATC2_spectral.py", line 590, in fit
    self.normalizer = JaccardNormalizer(A, self.coverage)
  File "SnapATC2_spectral.py", line 709, in __init__
    (slope, intersect) = jm_regress(jm, c)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: TooSteep

I also tried running the scATAnno_integrate function line by line to troubleshoot. It seems like everything runs properly until I get to this stage, which outputs the error above: 
if isinstance(sample_size, int):
            spectral(data_c, sample_size = sample_size, distance_metric = distance_metric) # default spectral component = 50
else:
            spectral(data_c, distance_metric = distance_metric)

One thing I also did differently is that I could not run this "python generate_reference_embedding.py --countMatrixLocation $output_path" in build_reference.sh. My output folder does not seem to have the "reference_embedding_spectral_model.model" file to run this line. I am not sure if this is causing the issue or not. 

Thank you again for all of your help and time! I really appreciate it.

Best,
Tri
